ccmbioinfo/cre

- gene.database/generate_c4r_db.pbs
- gene.database/generate_db_from_reports.py
- gene.database/pull_gene.py
- Added Burden field to database reports. Sample name for Zygosity and Burden fields can take on fam_samp or samp, resolves crashing.
- Rewrote all database scripts into 2 Python scripts. There is not longer any crashing due to encoding issues -- this is taken care of by Pandas. The script also consolidates sample specific data fields (like Zygosity) into a semi-colon delimited list
- Added variant Depth to report columns. Also included a TORQUE script.
> Add Dennis' gene.database scripts

- cre.vcf2cre.sh
when run in a folder already containing an ensembl db named by the project, a bug was causing it to get overwritten and moved
> fixing ensembldb deletion during re-run

- cre.sh
prevent synonymous reports from being run when wgs type specified
> fixing cre.sh oversight

- validation/README.md
- validation/compare_reports.pbs
- validation/gemini_compare.sh
1. `gemini_compare.sh` 
* accepts column names found only in one db. Output `<prefix>.uniq.db.txt` will have "0"  where the db does not have that column
2. `compare_reports.pbs`
* run one of the gemini query command with "&" (slight speed up)
* added calls to `validation_2020-11.py`
3. `README.md`
*  notes on bed file intersection for exome comparisons
*  notes on passing column names inside `compare_reports.pbs`
> Validate fix

- cre.vcf2db.R
This PR makes two SpliceAI columns, 'SpliceAI_impact' and 'SpliceAI_score'. 
The 'SpliceAI_score' column lists the maximum delta score of the acceptor gain, acceptor loss, donor gain, and donor loss for the variant. 
The 'SpliceAI_impact' lists the associated gene name, impact, and position for the maximum delta score in the format GENE|IMPACT|POSITION. If a variant falls in multiple genes, and has multiple spliceAI annotations, the annotation with the greatest delta score is selected.
> Parse SpliceAI annotation

- validation/validation_2020-11.py
use this to branch add/edit conditions to explain variants in "Cannot explain" category. 
newly added:
1. `min(depth) < 10`: explains variants previously excluded
2. `max(alt_depth) >= 3`: explains variants included in new reports
3. `clinvar_status != None`: explains variants newly added based on the Hillary `helrick/clinvar_updates` branch
4. `"-1" in alt_depth and "gatk" not in caller`: most of the "cannot explain" were called by freebayes/platypus and hence  missing AD/DP. Not very confident this is even a criteria anywhere, but keeping it for now.
> report-compare

- cre.gemini.variant_impacts.vcf2db.sh
The variant impact for variants with gnomad_af_popmax < 1% and LOW impact (e.g. synonymous, intronic) and non-empty clinvar_status was improperly queried, resulting in the 'Info' field for these variants being blank. This commit fixes that bug.
> fix variant impact bug

- cre.gemini.variant_impacts.vcf2db.sh
- cre.gemini2txt.vcf2db.sh
- cre.sh
- cre.vcf2cre.sh
- generate_reports.sh
This functionality can only be used if a .ped file is available for a trio. The information in the .ped file (i.e. parental information, affected status) is incorporated into the gemini db after the vcf is annotated. 
To generate the de novo report:
`generate_reports.sh <family> denovo <path to ped file>`
> create genome-wide de novo report

- validation/rtg-validations.pbs
500g of requested memory was sending this job to the bigmem queue unnecessarily: changed these requirements to 40g and Xmx=30g so that it can be picked up and run faster.
> Fixed mem issue for the validation RTG vcfeval script

- cram2fastq_samtools.pbs
Singleton reads must be written to a separate file so that R1 and R2 reads stay and sync, and bwa doesn't throw errors.
> write singleton reads to separate file

- cre.vcfanno.conf
- Removed current CADD annotation from the dbNSFP block in the vcfanno config.
- Added in new CADD annotation blocks to the vcfanno config from the full genome SNV and indel tsv files.
> Adding genome-wide CADD scores.

- validation/validation_2021-10.py
This is to fix an issue that arose when comparing synonymous reports - some variants in the platypus table file have 2 comma-separated values in the AD column which threw an error with the validation_2021-10.py script. I enabled the parse_ad functionality for the platypus file to solve this issue.
> added line to parse multiple platypus AD values

- cre.gemini.variant_impacts.vcf2db.sh
- cre.gemini2txt.vcf2db.sh
- cre.sh
The changes here are the following:
- Probands are defined as any individual in a pedigree that has values for maternal_id and paternal_id populated, regardless of affected status
- Parental IDs are derived from the proband's maternal_id and paternal_id fields
This means we can create de novo reports for multi-proband families, e.g. quads; the de novo report will contain putative de novo variants for each proband. A 'proband' here is defined as having both parents present, so de novo variants from unaffected siblings will be included.
> Create denovo report with variants from multiple probands

- cre.sh
Creates option to specify the reference as an argument to cre.sh, while using /hpf/largeprojects/ccmbio/naumenko/tools/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa as a default if no reference is specified. This allows us to provide a different reference path on the CHEO-RI space.
> Add reference argument

- cre.sh
This directory was accidentally deleted following the deletion of the dccforge/results cleanup. We have retrieved the C4R exome counts and HGMD databases from the CHEO-RI space, and copied them to the central crg2 annotations directory. Submitting this PR to change the cre database path prefix to that directory.
> changed default path to database files

- cre.gemini2txt.vcf2db.sh
- cre.vcf2db.R
- Modified cre.gemini2txt.vcf2db.sh and cre.vcf2db.R to create a new column in the report called "Dark_gene". If a variant falls in the dark region then the column contains the list of genes that fall in that region, else the column value is "None"
- This branch should be used in conjunction with crg2 (crg2-hg38-pacbio-dark-regions) branch
> Dark region annotation for PacBio reports

- cre.gemini2txt.vcf2db.sh
- cre.vcf2db.R
Add non-coding scores (nCER, ReMM, LINSIGHT) to WGS reports (panel, panel-flank, de novo). Scores are not added for exomes or WGS coding reports.
> add ncER, ReMM, and LINSIGHT scores

- cre.gemini2txt.vcf2db.sh
- cre.vcf2db.R
- data/orphanet.txt
Add non-coding scores: ReMM, ncER, LINSIGHT and AlphaMissense into annotation pipeline
> add non-coding scores

- cre.gemini2txt.vcf2db.sh
- cre.vcf2db.R
- For testing, please checkout crg2 branch "crg2-hg38-alphamissense" branch and cre branch "hg38-alphamissense".
- Tested pipeline on one genome from Mital Lab and Alphamissense annotation column was successfully added to the report (wes.regular) as well as the annotated VCF file.
> Alphamissense annotation for hg38

- cre.gemini2txt.vcf2db.sh
Add details of ClinVar conflicting status using the CLNSIGCONF field in the ClinVar VCF. For example, instead of just annotating a variant as `Conflicting_classifications_of_pathogenicity` it would be annotated as `Conflicting_classifications_of_pathogenicity;Uncertain_significance(2)|Likely_benign(3)`. Associated with [crg2 PR #236](https://github.com/ccmbioinfo/crg2/pull/236).
> Add ClinVar conflicting statuses

- cre.gemini.variant_impacts.vcf2db.sh
- cre.gemini2txt.vcf2db.sh
Variant GRCh38:chr6:g.26092913G>A was excluded from the wes.regular report in an individual because the clinvar_status was 'Pathogenic/Pathogenic,_low_penetrance|other|risk_factor', so it did not match one of 'Pathogenic', 'Likely_pathogenic', or 'Conflicting_interpretations_of_pathogenicity'. I revised the SQL query to include any variant with a clinvar_status (converted to lower case) containing the string 'pathogenic'.
> Make matching for variants in ClinVar with gnomad_af_popmax > 1% more permissive
